### ISSUE TITLE
通学路のデータの追加

### ISSUE THREAD

**Issue by taisukef** [code4fukui/kidssafe-yoshino#3]
https://github.com/code4fukui/kidssafe-yoshino/issues/1#issuecomment-2293185538

**Comment by taisukef** [comment]
1. GeoJSONの部分だけを scoolzone.geojson ファイルとして保存して、アップロードします
https://github.com/code4fukui/kunitaka/blob/main/schoolzone.geojson
国高の例

2. プログラム index.html で、geojsonファイルを読み込んでレイヤーを追加します
https://github.com/code4fukui/kunitaka/blob/main/index.html#L362-L376
国高の例

**Comment by yuta20240709** [comment]
ありがとうございます。できました

**Comment by taisukef** [comment]
おおー、すごい！
<img width="1108" alt="image" src="https://github.com/user-attachments/assets/cb2df025-560e-418c-8e7e-cd5235653cb8">
